version: '3.7'
services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=kdc_db
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
     - ./db_volumes:/var/lib/mysql
    ports:
     - '3306:3306'